taskapp/urls.py
from django.urls import path
from django.conf.urls import url,include
from taskapp import views
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings
#from taskapp.views import AutocompleteJsonView
urlpatterns = [
    path('', views.home,name='home'),

    # Team urls
    url(r'^team/create/$', views.teamreg,name='teamreg'),
    url(r'^team/view/(?P<string>.+)/$', views.teamview,name='teamview'),
    url(r'^team/edit/(?P<string>.+)/$', views.teamedit,name='teamedit'),
    
    # Task urls
    url(r'^task/create/$', views.taskreg,name='taskreg'),
    url(r'^task/view/(?P<string>.+)/$', views.taskview,name='taskview'),
    url(r'^task/edit/(?P<string>.+)/$', views.taskedit,name='taskedit'),
    url(r'^task/delete/(?P<string>.+)/$', views.taskdelete,name='taskdelete'),
    
    # Comments urls
    url(r'^comment/edit/(?P<id>[\w\-]+)/$', views.commentedit,name='commentedit'),
    url(r'^comment/delete/(?P<id>[\w\-]+)/$', views.commentdel,name='commentdel'),
    
    # Ajax requests urls
    url(r'^ajax/users/$', views.users_list, name='users_list'),
    url(r'^ajax/team/users/$', views.team_users_list, name='team_users_list'),
    url(r'^ajax/teams/$', views.teams_list, name='teams_list'),
    
]

taskproject/urls.py
from django.urls import path
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from taskapp import views
urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name="registration/login.html"), name='login'),
    #url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout/$', LogoutView.as_view(template_name="registration/logout.html"),name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^admin/', admin.site.urls),
    path('',include('taskapp.urls')),
]

taskapp/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone


class Team(models.Model):
    class Meta:
        verbose_name = _("Team")
        verbose_name_plural = _("Teams")
    title = models.CharField(_("title"), max_length=200)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='team_created', verbose_name=_('created by'),
                                   on_delete=models.SET_NULL, null=True)
    users = models.ManyToManyField(User)
    
    def __str__(self):
        return self.title

class Task(models.Model):
    class Meta:
        verbose_name = _("Task")
        verbose_name_plural = _("Tasks")
    
    STATUSES = (
        ('to-do', _('To Do')),
        ('planned', _('Planned')),
        ('in_progress', _('In Progress')),
        ('done', _('Done')),
        ('dismissed', _('Dismissed'))
    )

    title = models.CharField(_("title"), max_length=50)
    description = models.TextField(max_length=1000)
    team = models.ForeignKey(Team,on_delete=models.PROTECT, null =True, blank = True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='task_creator', verbose_name=_('task_creator'),
                                   on_delete=models.PROTECT, null=False)
    # assignee = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='task_assigne', verbose_name=_('task_assigne'),
    #                               on_delete=models.SET_NULL, null=True,blank=True)
    assignee = models.ManyToManyField(User,related_name='task_assigne', verbose_name=_('task_assigne'), null=True,blank=True)
    status = models.CharField(_("status"), max_length=20, choices=STATUSES,default='to-do')
    created_at = models.DateTimeField(_("created at"), auto_now_add=True, editable=False)
    last_modified = models.DateTimeField(_("last modified"), auto_now=True, editable=False)
    
    def __str__(self):
        return self.title
    def get_assignee(self):
        return ",".join([str(a) for a in self.assignee.all()])

class Comments(models.Model):
    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comment_creator', verbose_name=_('comment_creator'),
                                   on_delete=models.PROTECT, null=False)
    comment = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.comment

taskapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Team, Task, Comments
from django.contrib.auth.models import Group, User
from django.utils.translation import ugettext_lazy as _
from .choices import *
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('title', 'users',)

class TaskForm(forms.ModelForm):
    title = forms.CharField(max_length=50)
    description = forms.CharField(label="Description",max_length=100, widget=forms.Textarea)
    status = forms.ChoiceField(choices = STATUSES, label="Status", initial='', widget=forms.Select(), required=True)

    class Meta:
        model = Task
        fields = ('title', 'description', 'team', 'status', 'assignee',)
    
    # def __init__(self, user, *args, **kwargs):
    #     super(TaskForm, self).__init__(*args, **kwargs)

class TaskEditForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title','description', 'assignee','status')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('comment',)

taskapp/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignUpForm, TeamForm, TaskForm, TaskEditForm, CommentForm
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from django.contrib.auth.models import Group, User
import simplejson as json
from .models import Team, Task, Comments
from django.contrib.auth.decorators import login_required
from django import forms
from django.utils import timezone

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

"""

Home View where the current user can get all the information like
-> In which teams he is a member
-> Teams created by him
-> Tasks created by him
-> Tasks assigned to him
-> Tasks of his team

"""

def home(request):
    if request.user.is_anonymous:
        return render(request,'home.html')
    teams = [team for team in Team.objects.all() if request.user in team.users.all()]
    teams_created = [team for team in Team.objects.all() if request.user == team.created_by]
    tasks_created = [task for task in Task.objects.all() if request.user == task.created_by]
    tasks_assigned = [task for task in Task.objects.all() if request.user == task.assignee]
    my_team_tasks = []
    for team in teams:
        for task in Task.objects.all():
            if task.team == team:
                my_team_tasks.append(task)
    return render(request,'home.html', {'teams': teams,'teams_created': teams_created, 'tasks_created': tasks_created,'tasks_assigned': tasks_assigned,'my_team_tasks': my_team_tasks})

@login_required
def users_list(request):
    username = request.GET.get('username', None)
    id = request.user.id
    user = User.objects.filter(id=id)
    all_users = User.objects.all().order_by('id').exclude(id=id)
    return JsonResponse({
            'results': [
                #{'text': str(obj.username)}
                {'id': str(obj.id), 'text': str(obj.username)}
                for obj in all_users
            ],
        })

"""
Team registration ## only authenticated users can do it
"""

@login_required
def teamreg(request):
    if request.method == "POST":
        form = TeamForm(request.POST)
        if form.is_valid():
            users = form.cleaned_data['users']
            teamtitle = request.POST.get('title')
            team = form.save(commit=False)
            team = Team.objects.create()
            team.title = teamtitle
            for user in users:
                team.users.add(user)
            team.users.add(request.user)
            team.created_by = request.user
            team.save()
            return redirect('home')
        else:
            return HttpResponse('form invalid')
    else:
        form = TeamForm()
    return render(request, 'registration/team.html', {'form': form})

"""
View to edit team and render the updated team
"""

def teamedit(request, string):
    team = get_object_or_404(Team, title=string)
    if str(request.user) != str(team.created_by):
        return HttpResponse("You don't have permission to edit")
    if request.method == "POST":
        form = TeamForm(request.POST, instance=team)
        if form.is_valid():
            users = form.cleaned_data['users']
            teamtitle = request.POST.get('title')
            team.title = teamtitle
            team.users.clear()
            for user in users:
                if str(user)!=str(request.user):
                    team.users.add(user)
            team.users.add(request.user)
            team.save()
            return redirect('teamview', string=team.title)
    else:
        form = TeamForm(instance=team)
    return render(request, 'registration/teamedit.html', {'form': form})

'''
Get the team and check if request.user is team creator or not by using see variable.
'''

def teamview(request, string):
    team = get_object_or_404(Team, title=string)
    if team is None:
        return HttpResponse("Team not found")
    if str(request.user) == str(team.created_by):
        see = 1
    else:
        see = 0
    teammates = [val for val in team.users.all() if val in team.users.all()]
    return render(request, 'teamview.html', {'team': team, 'teammates': teammates, 'see': see})

# ajax to fetch users list of a team in task creation page  
@login_required
def team_users_list(request):
    id = request.GET.get('team', None)
    team = get_object_or_404(Team, id=id)
    all_users = [val for val in team.users.all() if val in team.users.all()]
    data = {
            str(obj.id) : str(obj.username)
            for obj in all_users
        },
    print(json.dumps(data))
    return JsonResponse(data,safe=False)

# teams list as ajax to fetch teams list where the user is member # team creator is also a member
@login_required
def teams_list(request):
    teams = [team for team in Team.objects.all() if request.user in team.users.all()]
    all_teams = teams
    data = {
            str(obj.id) : str(obj.title)
            for obj in all_teams
        },
    print(json.dumps(data))
    return JsonResponse(data,safe=False)


@login_required
def taskreg(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            tasktitle = request.POST.get('title')
            desc = request.POST.get('description')
            teamid = request.POST.get('team')
            asignes = form.cleaned_data['assignee']
            state = request.POST.get('status')
            created_by = request.user
            created_at = timezone.now()
            last_modified = timezone.now()

            # if team is empty then assignee has to be the request.user always
            if teamid=="":
                Task.objects.create(title=tasktitle,description=desc,created_by=created_by,status=state,created_at=created_at,last_modified=last_modified)
                task = get_object_or_404(Task, title=tasktitle)
                task.assignee.add(request.user)
                return redirect('taskview', string=task.title)
            else:
                team = Team.objects.get(id=teamid)
                # no assignee at present we'll add later
                Task.objects.create(title=tasktitle,description=desc,created_by=created_by,team=team,status=state,created_at=created_at,last_modified=last_modified)
            task = get_object_or_404(Task, title=tasktitle)
            #So, we have a team assigned for task
            for user in asignes:
                task.assignee.add(user)
            task.save()
            return redirect('taskview', string=task.title)
        else:
            return HttpResponse('form invalid')
    else:
        form = TaskForm(request.user)
    return render(request, 'task.html', {'form': form})



"""
View to edit task and render the updated task
"""
@login_required
def taskedit(request, string):
    task = get_object_or_404(Task, title=string)
    taskprev = task
    if str(request.user) != str(task.created_by):
        return HttpResponse("You don't have permission to edit")
    if request.method == "POST":
        form = TaskEditForm(request.POST, instance=task)
        # no assignee 
        if(request.POST.get('assignee')==""):
            task.assignee.clear()
            tasktitle = request.POST.get('title')
            taskdesc = request.POST.get('description')
            task.title = tasktitle
            task.description = taskdesc

            state = request.POST.get('status')
            task.status = state
            task.last_modified = timezone.now()
            task.save()
            comm = Comments.objects.filter(task = taskprev)
            # changing comments related to task when task is changed
            for com in comm:
                com.task = task
                com.save()
            return redirect('taskview', string=task.title)         
        # assignee is there
        if form.is_valid():
            tasktitle = request.POST.get('title')
            taskdesc = request.POST.get('description')
            task.title = tasktitle
            task.description = taskdesc
            #asigne = request.POST.get('assignee')
            #                 
            if(request.POST.get('assignee')==""):
                task.assignee.clear()
            else:
                asignes = form.cleaned_data['assignee']
                task.assignee.clear()
                for user in asignes:
                    task.assignee.add(user)
            state = request.POST.get('status')
            task.status = state
            task.last_modified = timezone.now()
            task.save()
            comm = Comments.objects.filter(task = taskprev)
            # changing comments related to task when task is changed
            for com in comm:
                com.task = task
                com.save()
            return redirect('taskview', string=task.title)
        else:
            return HttpResponse("form invalid")
    else:
        form = TaskEditForm(instance=task)
        team = get_object_or_404(Team, id=task.team.id)
        users = [val for val in team.users.all() if val in team.users.all()]
        assignes = task.assignee
        a = [val for val in task.assignee.all() if val in task.assignee.all()]
    return render(request, 'taskedit.html', {'form': form, 'task': task, 'users': users, 'a': a})


"""
View which allows specific users to view the task 
"""
@login_required
def taskview(request, string):

taskapp/templates/base.html
<!DOCTYPE html>
<head>
    {% load static %}
    <meta charset="utf-8" />
    <title>Task Manager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css/index.css" %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

    {% block content %}
    {% endblock %}
    
</body>
</html>

taskapp/templates/commentedit.html
{% extends 'base.html' %}

{% block content%}
<br><br>
    <div class="container" style="background-color:aliceblue;">
        <div class="row">
            <div class = "col-md-4" style=" text-align: left;">
                <a href="{% url 'home' %}"><h2>🏠Home</h2></a>
            </div>
            <div class = "col-md-8" style=" text-align: right;">
                <h3>Commented under task "{{comment.task}}" on "{{comment.created_date}}"</h3>
            </div>
        </div>
    </div>
    
    <br>
    <div class="container" style="background-color:#b7e0f5;">
        <form method="post">
                {% csrf_token %}
 
                <div class="form-group">
                        <label for="id_comment">Comment:</label> 
                        <textarea class="form-control" name="comment" rows="5" maxlength="1000" required="" id="id_comment" aria-describedby="comHelp" placeholder="Enter Comment">{{comment.comment}}</textarea>
                        <small id="comHelp" class="form-text text-muted">Please enter the comment for task.</small>
                </div>
                <button type="submit" class="btn btn-primary">Update Comment</button>
                <a href="{% url 'home' %}" class="btn btn-primary" role="button" aria-pressed="true">Cancel</a>
            {% if comment.author == request.user %}
                <a href="{% url 'commentdel' id=comment.id %}" class="btn btn-primary" role="button" aria-pressed="true">Delete Comment ?</a>
            {% endif %}
        </form>
        <br><br>
    </div>
{% endblock %}

taskapp/templates/task.html
<html>
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>Create Task</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
      <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
   </head>


<body>
    <br><br>
    <div class="container" style="background-color:aliceblue;">
        <div class="row">
            <div class = "col-md-12" style=" text-align: left;">
                <h2><a href="{% url 'home' %}">🏠Home</a></h2>
            </div>
        </div>
    </div>    
  <div class="container">

    <br><h1>Create Task</h1><br>

    <form method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="id_title">Title :</label>
        <input type="text" class="form-control" name="title" maxlength="50" required="" id="id_title" aria-describedby="titleHelp" placeholder="Enter Task Title">
        <small id="titleHelp" class="form-text text-muted">Please enter the appropriate title for task.</small>
      </div>
      
      <div class="form-group">
        <label for="id_description">Description:</label> 
        <textarea class="form-control" name="description" rows="5" maxlength="1000" required="" id="id_description" aria-describedby="descHelp" placeholder="Enter Task Description"></textarea>
        <small id="descHelp" class="form-text text-muted">Please enter the brief description for task.</small>
      </div>
      
      <div class="form-group">
        <label for="id_team">Team :</label>
        <select class="form-control" name="team" id="id_team" aria-describedby="teamHelp">
          <option value="" selected="">---------</option>
        </select>
        <small id="teamHelp" class="form-text text-muted">Please select team, if you are not in any team leave it blank.</small>
      </div>
      
      <div class="form-group">
        <label for="id_status">Status :</label>
        <select class="form-control" required="" name="status" id="id_status" aria-describedby="statusHelp">
            <option value="to-do">To Do</option>
              <option value="planned">Planned</option>
              <option value="in_progress">In Progress</option>
              <option value="done">Done</option>
              <option value="dismissed">Dismissed</option>
        </select>
        <small id="statusHelp" class="form-text text-muted">Please select the present status of Task.</small>
      </div>
      
      <div class="form-group">
        <label for="id_assignee">Task Assigne :</label>
        <select class="form-control" name="assignee" id="id_assignee" aria-describedby="assignHelp" multiple>
          <option value="" selected="">---------</option>
        </select>
        <small id="assignHelp" class="form-text text-muted">Please select assignee, if you are not in any team you will be automatically assigned.</small>
      </div>
      
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
  </div>


      <br><br><br>
      {% block javascript %}
      <script type="text/javascript">
         $( document ).ready(function() {
         
           var $id_assignee = $('#id_assignee');
             $id_assignee.empty();
             $id_assignee.append('<option value="{{request.user.id}}" selected="">{{request.user.username}}</option>');
         
             //console.log( "ready!" );
             $.ajax({
               url: "/ajax/teams/",
               dataType: 'json',
               success: function(data) {
                 var t = data[0]
                 for (var key in t) {
                   if (t.hasOwnProperty(key)) {
                     var val = t[key];
                     console.log(key,val);
                   }
                 }
                 //<option value="1">team</option>
                 var $id_team = $('#id_team');
                   $id_team.empty();
                   $id_team.append('<option value="" selected="">---------</option>');
                   for (var key in t) {
                     if (t.hasOwnProperty(key)) {
                       $id_team.append('<option value=' + key + '>' + t[key] + '</option>');
                     }
                   }
         
               }});
         
           });
         
         $(document).ready(function(){
           $('#id_team').change(function(){
           var e = document.getElementById("id_team");
           var team = e.options[e.selectedIndex].value;
           console.log(team)
           $.ajax({
               url: "/ajax/team/users/",
               data: {
                 'team': team
               },
               dataType: 'json',
               success: function(data) {
                 var t = data[0]
                 
                 console.log(data[0])
                 for (var key in t) {
                   if (t.hasOwnProperty(key)) {
                     var val = t[key];
                     console.log(key,val);
                   }
                 }
         
                 var $id_assignee = $('#id_assignee');
                   $id_assignee.empty();
                  //  $id_assignee.append('<option value="" selected="">---------</option>');
                   for (var key in t) {
                     if (t.hasOwnProperty(key)) {
                       $id_assignee.append('<option value=' + key + '>' + t[key] + '</option>');
                     }
                   }
               }});
         
           });
         });
      </script>
      {% endblock %}
   </body>
</html>

taskapp/templates/taskedit.html
{% extends 'base.html' %}

{% block title %}Edit Team{% endblock %}

{% block content %}
<br><br>
    <div class="container" style="background-color:aliceblue;">
        <div class="row">
            <div class = "col-md-3" style=" text-align: left;">
                <a href="{% url 'home' %}"><h2>🏠Home</h2></a>
            </div>
            <div class = "col-md-3" style=" text-align: left;">
                <h3>Status : {{task.status}}</h3>
            </div>
            <div class = "col-md-3" style=" text-align: right;">
                <h3>Assignee : {% for assignee in a %}{{assignee}} {% endfor %}</h3>
            </div>
            <div class = "col-md-3" style=" text-align: right;">
                <h3>Team : {{task.team}}</h3>
            </div>
        </div>
    </div> 
<br><br>
<div class="container">
  <form method="post">
      {% csrf_token %}

  <div class="form-group">
    <label for="id_title">Title :</label>
    <input type="text" class="form-control" name="title" value="{{task.title}}" maxlength="50" required="" id="id_title" aria-describedby="titleHelp" placeholder="Enter Task Title">
    <small id="titleHelp" class="form-text text-muted">Please enter the appropriate title for task.</small>
  </div>
  <div class="form-group">
      <label for="id_description">Description:</label> 
      <textarea class="form-control" name="description" rows="5" maxlength="1000" required="" id="id_description" aria-describedby="descHelp" placeholder="Enter Task Description">{{task.description}}</textarea>
      <small id="descHelp" class="form-text text-muted">Please enter the brief description for task.</small>
  </div>

  <div class="form-group">
      <label for="id_status">Status :</label>
      <select class="form-control" required="" name="status" id="id_status" aria-describedby="statusHelp">
        	<option value="to-do">To Do</option>
            <option value="planned">Planned</option>
            <option value="in_progress">In Progress</option>
            <option value="done">Done</option>
            <option value="dismissed">Dismissed</option>
      </select>
      <small id="statusHelp" class="form-text text-muted">Please select the present status of Task.</small>
  </div>

  <div class="form-group">
      <label for="id_assignee">Task Assigne :</label>
      <select class="form-control" name="assignee" id="id_assignee" aria-describedby="assignHelp" multiple>
        <option value="" selected="">---------</option>
        {% for a in users  %}
          <option value="{{a.id}}">{{a.username}}</option>
        {% endfor %}
      </select>
      <small id="assignHelp" class="form-text text-muted">Please select assignee, if you are not in any team you will be automatically assigned.</small>
  </div>

  <button type="submit" class="btn btn-primary">Update</button>
  <a href="{% url 'home' %}" class="btn btn-primary" role="button" aria-pressed="true">Cancel</a>
  <a href="{% url 'taskdelete' string=task.title %}" class="btn btn-primary" role="button" aria-pressed="true">Delete Task ?</a>
            
</form>
<br><br><br>
</div>
{% endblock %}

taskapp/templates/taskview.html
{% extends 'base.html' %}

{% block content %}
<br><br>
    <div class="container" style="background-color:aliceblue;">
        <div class="row">
            <div class = "col-md-4" style=" text-align: left;">
                <a href="{% url 'home' %}"><h2>🏠Home</h2></a>
            </div>
            <div class = "col-md-4" style=" text-align: center;">
                <h3>Assigned to : {% for assignee in a %}{{assignee}} {% endfor %}</h3>
            </div>
            <div class = "col-md-4" style=" text-align: right;">
                {% if task.created_by == request.user %}
                    <h3>Yay ! You are the task creator</h3>
                {% else %}
                    <h3>Task Creator : {{ task.created_by }}</h3>
                {% endif %}
            </div>
        </div>
    </div>
    
    <br>

    <div class="container" style="background-color:aliceblue;">   
        <div class="row">
            <div class="col-sm-12" style="text-align: left;">
                {% if task.created_by == request.user %}
                    <h3><a href="{% url 'taskedit' string=task.title %}">{{ task.title }}</a></h3>
                {% else %}
                    {{task.title}}
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4" style="text-align: left;">
                <h4>Status : {{task.status}}</h4>
            </div>
            <div class="col-sm-4" style="text-align: center;">
                <h4>Created at : {{task.created_at}}</h4>
            </div>
            <div class="col-sm-4" style="text-align: right;">
                <h4>Last Updated at : {{task.last_modified}}</h4>
            </div>
        </div>
    </div>
    <br><br>
    <div class="container" style="background-color:#b7e0f5;">
        <h3>Comments : </h3>
        {% for comment in comments %}
            <div class="row" style="background-color:#61c5f7;margin: 1%;">
                <div class="col-sm-12" style="text-align: left;">
                    <h5>{{comment.author}} commented on {{comment.created_date}}</h5>
                </div>
                <div class="col-sm-12" style="text-align: left;">
                    <h3>{{comment}}</h3>
                </div>
                {% if comment.author == request.user %}
                    <div class="col-sm-12" style="text-align: left;padding-bottom: 5px;">
                        <a href="{% url 'commentedit' id=comment.id %}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">Edit?</a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}
        <br>
        <form method="post">
                <div class="form-group">{% csrf_token %}
                  <label for="id_comment"></label> 
                  <textarea class="form-control" name="comment" cols="40" rows="10" required="" id="id_comment" placeholder="Enter your Comment here !"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Post Comment</button>
        </form>
        <br>
    </div>
      
{% endblock %}